[2025-03-31T23:44:58.630+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T23:44:59.230+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task manual__2025-03-31T23:44:42.226688+00:00 [queued]>
[2025-03-31T23:44:59.265+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task manual__2025-03-31T23:44:42.226688+00:00 [queued]>
[2025-03-31T23:44:59.265+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T23:44:59.293+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_task> on 2025-03-31 23:44:42.226688+00:00
[2025-03-31T23:44:59.324+0000] {standard_task_runner.py:72} INFO - Started process 945 to run task
[2025-03-31T23:44:59.356+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'decide_next_task', 'manual__2025-03-31T23:44:42.226688+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpcb1j2azj']
[2025-03-31T23:44:59.369+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask decide_next_task
[2025-03-31T23:44:59.566+0000] {task_command.py:467} INFO - Running <TaskInstance: 2-Cargar_data.decide_next_task manual__2025-03-31T23:44:42.226688+00:00 [running]> on host 45ab05f75c83
[2025-03-31T23:44:59.884+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='decide_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T23:44:42.226688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T23:44:42.226688+00:00'
[2025-03-31T23:44:59.888+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T23:44:59.926+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-31T23:45:04.958+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2025-03-31T23:45:04.960+0000] {branch.py:38} INFO - Branch into load_data
[2025-03-31T23:45:04.962+0000] {skipmixin.py:233} INFO - Following branch ('load_data',)
[2025-03-31T23:45:05.011+0000] {skipmixin.py:281} INFO - Skipping tasks [('stop_task', -1)]
[2025-03-31T23:45:05.119+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T23:45:05.121+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=decide_next_task, run_id=manual__2025-03-31T23:44:42.226688+00:00, execution_date=20250331T234442, start_date=20250331T234459, end_date=20250331T234505
[2025-03-31T23:45:05.331+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T23:45:05.399+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T23:45:05.402+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
