[2025-03-31T23:44:36.382+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T23:44:37.022+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:44:20+00:00 [queued]>
[2025-03-31T23:44:37.050+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:44:20+00:00 [queued]>
[2025-03-31T23:44:37.050+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T23:44:37.077+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_task> on 2025-03-31 23:44:20+00:00
[2025-03-31T23:44:37.118+0000] {standard_task_runner.py:72} INFO - Started process 929 to run task
[2025-03-31T23:44:37.132+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'decide_next_task', 'scheduled__2025-03-31T23:44:20+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpbtgo351i']
[2025-03-31T23:44:37.142+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask decide_next_task
[2025-03-31T23:44:37.377+0000] {task_command.py:467} INFO - Running <TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:44:20+00:00 [running]> on host 45ab05f75c83
[2025-03-31T23:44:37.644+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='decide_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T23:44:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T23:44:20+00:00'
[2025-03-31T23:44:37.661+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T23:44:37.737+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-31T23:44:42.802+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2025-03-31T23:44:42.804+0000] {branch.py:38} INFO - Branch into load_data
[2025-03-31T23:44:42.807+0000] {skipmixin.py:233} INFO - Following branch ('load_data',)
[2025-03-31T23:44:42.845+0000] {skipmixin.py:281} INFO - Skipping tasks [('stop_task', -1)]
[2025-03-31T23:44:43.006+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T23:44:43.007+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=decide_next_task, run_id=scheduled__2025-03-31T23:44:20+00:00, execution_date=20250331T234420, start_date=20250331T234437, end_date=20250331T234443
[2025-03-31T23:44:43.222+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T23:44:43.296+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T23:44:43.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
