[2025-03-31T23:37:25.665+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T23:37:26.580+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:37:10+00:00 [queued]>
[2025-03-31T23:37:26.620+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:37:10+00:00 [queued]>
[2025-03-31T23:37:26.621+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T23:37:26.684+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_task> on 2025-03-31 23:37:10+00:00
[2025-03-31T23:37:26.748+0000] {standard_task_runner.py:72} INFO - Started process 589 to run task
[2025-03-31T23:37:26.808+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'decide_next_task', 'scheduled__2025-03-31T23:37:10+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpb3hb411c']
[2025-03-31T23:37:26.849+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask decide_next_task
[2025-03-31T23:37:27.282+0000] {task_command.py:467} INFO - Running <TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:37:10+00:00 [running]> on host 45ab05f75c83
[2025-03-31T23:37:27.891+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='decide_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T23:37:10+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T23:37:10+00:00'
[2025-03-31T23:37:27.898+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T23:37:28.026+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-31T23:37:33.126+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2025-03-31T23:37:33.128+0000] {branch.py:38} INFO - Branch into load_data
[2025-03-31T23:37:33.131+0000] {skipmixin.py:233} INFO - Following branch ('load_data',)
[2025-03-31T23:37:33.179+0000] {skipmixin.py:281} INFO - Skipping tasks [('stop_task', -1)]
[2025-03-31T23:37:33.365+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T23:37:33.369+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=decide_next_task, run_id=scheduled__2025-03-31T23:37:10+00:00, execution_date=20250331T233710, start_date=20250331T233726, end_date=20250331T233733
[2025-03-31T23:37:33.530+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T23:37:33.628+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T23:37:33.633+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
