[2025-04-01T18:05:32.733+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T18:05:33.822+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task manual__2025-04-01T18:03:18.492702+00:00 [queued]>
[2025-04-01T18:05:33.871+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task manual__2025-04-01T18:03:18.492702+00:00 [queued]>
[2025-04-01T18:05:33.874+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-01T18:05:33.945+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_task> on 2025-04-01 18:03:18.492702+00:00
[2025-04-01T18:05:33.995+0000] {standard_task_runner.py:72} INFO - Started process 357 to run task
[2025-04-01T18:05:34.019+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'decide_next_task', 'manual__2025-04-01T18:03:18.492702+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpff6p0s02']
[2025-04-01T18:05:34.034+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask decide_next_task
[2025-04-01T18:05:34.209+0000] {task_command.py:467} INFO - Running <TaskInstance: 2-Cargar_data.decide_next_task manual__2025-04-01T18:03:18.492702+00:00 [running]> on host 111d26a6d12f
[2025-04-01T18:05:34.570+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='decide_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T18:03:18.492702+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T18:03:18.492702+00:00'
[2025-04-01T18:05:34.579+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T18:05:34.636+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-01T18:05:39.680+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2025-04-01T18:05:39.680+0000] {branch.py:38} INFO - Branch into load_data
[2025-04-01T18:05:39.684+0000] {skipmixin.py:233} INFO - Following branch ('load_data',)
[2025-04-01T18:05:39.733+0000] {skipmixin.py:281} INFO - Skipping tasks [('stop_task', -1)]
[2025-04-01T18:05:39.816+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T18:05:39.817+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=decide_next_task, run_id=manual__2025-04-01T18:03:18.492702+00:00, execution_date=20250401T180318, start_date=20250401T180533, end_date=20250401T180539
[2025-04-01T18:05:39.991+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T18:05:40.075+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-01T18:05:40.081+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
